/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coding.test.starter.Java;

import java.util.HashMap;
import java.util.Map;

public class App {
    public Map<String, Integer> getNotes() {
        return new HashMap<>();
    }

    public static void main(String[] args) {
        System.out.println("Do what you need");
    }
}
