/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coding.test.starter.Java;

public class App {
    public void getNotes() {
        return;
    }

    public static void main(String[] args) {
        System.out.println("Do what you need");
    }
}
