/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coding.test.starter.Java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void getNotesN() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getNotes(), "answer should be ...");
    }
}
